version: "3.8"

networks:
  app_net:
    driver: bridge

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    image: crud-app
    container_name: web-app
    command: python3 manage.py runserver 0.0.0.0:8000
    networks:
      - app_net
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
       - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_net

  prometheus:
    image: prom/prometheus:main
    ports:
      - "9090:9090"
    networks:
      - app_net


volumes:
  pgdata: